== Prerequisites

As prerequisites to perform the workshop, you need to have the following tools installed on your laptop:

- JDK 8+
- Maven 3
- Docker
- `kubectl`
- https://cloud.ibm.com/docs/home/tools[IBM Cloud CLI^] (`ibmcloud`)
// Emily, try out (Mac OS & Win (colleagues))
- `curl`


=== IBM Cloud account

TODO

- ibmcloud login
- create Kubernetes cluster
- install Istio
- connect to cluster
- test with `kubectl cluster-info`, `kubectl get nodes`, `kubectl get pods --all-namespaces`

==== Container Registry

We log into the Container Registry service via the `ibmcloud` CLI:

----
ibmcloud cr login
----

We use the CLI to create a namespace in the Container Registry service (`cr`) for our workshop:

----
ibmcloud cr region
ibmcloud cr namespace-add istio-workshop
ibmcloud cr namespaces
----

In order to test our new registry namespace, we pull a public image, re-tag it for our own registry, and push it:

TODO change to actual Open Liberty image

----
docker pull open-liberty:javaee8
docker tag open-liberty:javaee8 registry.eu-de.bluemix.net/istio-workshop/open-liberty:1
docker push registry.eu-de.bluemix.net/istio-workshop/open-liberty:1
----

Let's see whether our image is now in the private registry:

----
ibmcloud cr images
----


=== Local Docker setup

If you want to try out the example locally, you have to create a Docker network similar to the following:

----
docker network create --subnet=192.168.42.0/24 dkrnet
----
