== Conclusion

We've now seen some of the benefits of cloud native technologies in action.

Containers and Docker simplifies and unifies the way how we build and ship our application binaries.
Orchestration and Kubernetes organizes our workloads across large cluster environments and provides abstractions for our microservices.
Services meshes and Istio enables us to enhance our services and add required cross-cutting concerns in a transparent way, without much change on our side.
They also improve the testability of applications, by making it possible to inject failures and delays to provoke error situations.

You've seen how to integrate our Enterprise Java applications into cloud native technologies.
You have access to all code examples and infrastructure-as-code snippets.
Now, take your learnings further and go build something cool!


=== Further resources

- https://www.eclipse.org/community/eclipse_newsletter/2018/september/MicroProfile_istio.php[MicroProfile on Istio^]
- https://blog.sebastian-daschner.com/entries/istio-networking-api-explained[Istio Networking API explained^]
- https://blog.sebastian-daschner.com/entries/zero-downtime-updates-kubernetes[Zero-downtime deployments with Kubernetes^]
- https://blog.sebastian-daschner.com/entries/zero-downtime-updates-istio[Zero-downtime deployments with Istio^]
- https://docs.docker.com/engine/reference/builder/[Dockerfile reference^]
- https://kubernetes.io/docs/home/[Kubernetes documentation^]
- https://istio.io/docs/[Istio docs^]
- https://medium.com/kialiproject/different-mesh-visualizations-in-kiali-82a3428ae155[Visualizations in Kiali^]
