kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: v2
    spec:
      containers:
      - name: coffee-shop
        image: registry.eu-gb.bluemix.net/daschner/coffee-shop:2
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -f http://localhost:9080/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/health | grep -q coffee-shop"]
          initialDelaySeconds: 40
      restartPolicy: Always
---
