kind: Service
apiVersion: v1
metadata:
  name: barista
  labels:
    app: barista
spec:
  selector:
    app: barista
  ports:
    - port: 9080
      name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: barista
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: barista
        version: v1
    spec:
      containers:
      - name: barista
        image: registry.eu-gb.bluemix.net/daschner/barista:1
        ports:
        - containerPort: 9080
        livenessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/"]
          initialDelaySeconds: 20
        readinessProbe:
          exec:
            command: ["sh", "-c", "curl -s http://localhost:9080/health | grep -q barista"]
          initialDelaySeconds: 40
      restartPolicy: Always
---
