kind: Service
apiVersion: v1
metadata:
  name: barista
  labels:
    app: barista
spec:
  selector:
    app: barista
  ports:
    - port: 9080
      name: http
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: barista
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: barista
        version: v1
    spec:
      containers:
      - name: barista
        image: sdaschner/barista:12factor-1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        livenessProbe:
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 40
        readinessProbe:
          httpGet:
            path: /barista/resources/health
            port: 9080
          initialDelaySeconds: 60
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
